# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db15b7203667e05f3a211010e5c0766531035e5a05c4aeb67da8b178758a87075c7b166e3a16057cbf2038fccd958d2ff6f016aa321f2974b13212ec392ab81b

test:
  secret_key_base: 04d8ce2beb642c225616db8fec8e39788a96737b428f838776497761258a753f1f097087eba25a1af74445c1437ec09f3f9b36b3b8158cc8826ccff6fcd6d7ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
